name: Tailscale Network Setting
on:
  workflow_dispatch:
    inputs:
      tailscale_running_time:
        description: 'tailscale running minute'
        required: true
        default: 60
        type: number

jobs:
  parallel-commands:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Base Setting
        run: |
          echo "runner will be close after ${{ inputs.tailscale_running_time }} minute"
          sudo sysctl -w net.ipv6.conf.all.forwarding=1
          sudo sysctl -w net.ipv6.conf.default.forwarding=1

      - name: Setup Tailscale Device
        run: curl -fsSL https://tailscale.com/install.sh | sh
  
      - name: Run Tailscale Service
        env:
          TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY }}
        run: |
          echo $TAILSCALE_AUTHKEY
          sudo tailscale up \
            --authkey="${TAILSCALE_AUTHKEY}" \
            --hostname=github-runner-${{ github.repository_owner }}-${{ github.run_id }} \
            --advertise-exit-node

      - name: Setup tmate Session
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: ${{ inputs.tailscale_running_time }}
       

